on:
  push:
    branches: []

  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
env:
  CHOICE: "${{ inputs.choice }}"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ env.CHOICE }}